### ISSUE TITLE
SPARQL query generated by DPU is invalid

### ISSUE THREAD

**Issue by skrchnavy** [OpenDataNode/UVPlugin-rdfToCKAN#3]
_Note: Extracted second issue from #1_

SPARQL query it generates is invalid. For example, for the named graph `http://data.snk.sk/resource/dataset/bibliographic-database` it generates the following SPARQL query:

```
select {?s ?p ?o} from http://data.snk.sk/resource/dataset/bibliographic-database
```

The correct SELECT query should be instead:

```
SELECT *
WHERE {
  GRAPH <http://data.snk.sk/resource/dataset/bibliographic-database> {
    ?s ?p ?o .
  }
} 
```

Even better, since we're dealing with RDF a CONSTRUCT query would be more suitable, because it produces RDF instead of the triple table:

```
CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  GRAPH <http://data.snk.sk/resource/dataset/bibliographic-database> {
    ?s ?p ?o .
  }
} 
```

The best solution might actually be to use [SPARQL HTTP Graph Store protocol](http://www.w3.org/TR/sparql11-http-rdf-update/) by passing the graph URI as a value of the `graph` query parameter to the `http://localhost:8890/sparql-graph-crud` endpoint.

```
http://localhost:8890/sparql-graph-crud?graph=http%3A%2F%2Fdata.snk.sk%2Fresource%2Fdataset%2Fbibliographic-database
```

Note that none of the methods above should be used for larger datasets (e.g., more that tens of MB or million of triples). In such cases, the data dump should not be generated on demand but instead served from a static, pre-generated file.

Context: I'm using ODN 1.0.1 installed from the odn-simple Debian package, which contains this DPU in version 1.0.1 (uv-l-rdfToCkan-1.0.1.jar).

**Comment by ghost** [comment]
This query is in ckan properties file:

```
$ cat /etc/odn-simple/odn-ckan-ic/production.ini | grep odn.storage.rdf.uri.template
odn.storage.rdf.uri.template = http://odn-trencin:8890/sparql?default-graph-uri={storage_id}&qtxt=select * where {?s ?p ?o} limit 1000
```

and has nothing to do with this DPU.

**Comment by skrchnavy** [comment]
@mkl-eea-sk please check if it is possible to update `odn.storage.rdf.uri.template` to contain in `qtxt` variable the proposed URL.
_(@jindrichmynarz is there another option ? You have proposed these queries in #1)_

**Comment by ghost** [comment]
Which one? This?

```
http://localhost:8890/sparql-graph-crud?graph=http%3A%2F%2Fdata.snk.sk%2Fresource%2Fdataset%2Fbibliographic-database
```

Will this be OK for other projects ? (which customize /sparql endpoint ?)
Is it OK to change behavior? For now - user gets Form with graph prefilled. You propose direct download of data (no query edit). Does it make sense for sparql enpoint resource? when i want to download whole dataset, i would choose to download TTL file from dataset resource list...

please discuss with @eea04 @tomas-knap . Of course, the link you provided is invalid, but is bug in your installation and maybe your deploy team not knowing what is going around. I have been fixing this link at least 3 times for few last months... The one I have wrote here is valid  and discussed with @tomas-knap  to be OK for ODN.

**Comment by jindrichmynarz** [comment]
@skrchnavy: There are 2 alternatives, both of which are standardized by W3C ([SPARQL 1.1 Query](http://www.w3.org/TR/sparql11-query/) and [SPARQL 1.1 Graph Store](http://www.w3.org/TR/sparql11-http-rdf-update/)) and provided by default in Virtuoso. I have described both options in the issue above. The first option is to use SPARQL CONSTRUCT query, like this:

```
CONSTRUCT {
  ?s ?p ?o .
}
WHERE {
  GRAPH <http://data.snk.sk/resource/dataset/bibliographic-database> {
    ?s ?p ?o .
  }
} 
```

The second option is the provide the named graph URI as a query parameter to the SPARQL 1.1 Graph Store endpoint, like this:

```
http://localhost:8890/sparql-graph-crud?graph=http%3A%2F%2Fdata.snk.sk%2Fresource%2Fdataset%2Fbibliographic-database
```

As a side note, behind the scenes the second option may be implemented via the first option (see the illustrative CONSTRUCT query in the [specification](http://www.w3.org/TR/sparql11-http-rdf-update/#http-get)) but it can be implemented more efficiently than a CONSTRUCT query, which is why I think using the second option is preferable.

**Comment by jindrichmynarz** [comment]
> @mkl-eea-sk: Will this be OK for other projects ? (which customize /sparql endpoint ?)

SPARQL 1.1 Graph Store endpoint at `/sparql-graph-crud` (and `/sparql-graph-crud-auth` for authenticated access) is provided by default in Virtuoso. Users would have to take extra measures to disable or remap these URLs (I'm not aware of any way how to do that). Therefore, I think it is reasonable to expect that any instance of Virtuoso (and ODN) will provide these URL endpoints.

> @mkl-eea-sk: Is it OK to change behavior? For now - user gets Form with graph prefilled. You propose direct download of data (no query edit). Does it make sense for sparql enpoint resource? when i want to download whole dataset, i would choose to download TTL file from dataset resource list...

Good point. I have originally reported the issue because the way it was done was not working, not because I wanted to change the intended function. I proposed a way to fix it, however, changing the intended function. Now I understand the intended function was to be able to query the named graph easily and not download it. I agree that this is a better option.

However, the current implementation of this functionality is also problematic. When I load a dataset into a named graph with a given URI (i.e. not with an auto-generated one), I need to set this URI as a symbolic name in before the RDFDataUnit reaches l-rdfToCkan (e.g., in l-filesToRdf using the _Fixed output symbolic name_ parameter). This goes back to UnifiedViews/Plugins#225, especially the general discussion about where the named graph URI should be set (which I don't think was resolved). When I do this l-rdfToCkan creates 2 resources in CKAN. One is in the form of `http://{host}:8890/sparql?default-graph-uri={named graph URI}&qtxt=select%20*%20where%20%7B?s%20?p%20?o%7D%20limit%201000`, which is correct and what we want.

However, an additional resource is loaded with the URL in the form of `http://{host}:8890/sparql?default-graph-uri={auto-generated graph URI}&qtxt=select%20*%20where%20%7B?s%20?p%20?o%7D%20limit%201000`, where the auto-generated graph URI is something like `http://unifiedviews.eu/resource/sparql-construct/1436684305104`. This seems to be a URI generated by t-sparqlConstruct. It probably points out to an issue of t-rdfMerger which I use to merge RDF from t-filesToRdf and t-sparqlConstruct. It seems that t-rdfMerger produces 2 RDFDataUnits instead of one. Triples from the RDFDataUnits seem to be merged correctly, but not the RDFDataUnits (and their corresponding named graph URIs). Is my understanding correct? If so, I will raise this issue directly in the repository to t-rdfMerger, because it's an issue of t-rdfMerger and not l-rdfToCkan.

Nevertheless, there seems to be an issue of l-rdfToCkan. If I do not provide an fixed named graph URI (i.e. symbolic name), then for each pipeline execution a new CKAN resource is created, even though the auto-generated named graph URI remains the same. Why is the resource created in the previous pipeline execution not overwritten? When I provide a fixed named graph URI, the corresponding CKAN resource is correctly overwritten, but this is not the case without a fixed named graph URI. I wonder why the equality check does not work in that case and results in duplicated CKAN resources.

Context: I'm using ODN 1.0.3 installed from the odn-simple Debian package.

**Comment by ghost** [comment]
I am unable to understand last comment, I need skype call to help with resolution of this.

**Comment by jindrichmynarz** [comment]
We clarified this issue with @mkl-eea-sk via Skype.

l-rdfToCkan's side is mostly fine, however, there is an issue in t-rdfMerger, which I have reported in UnifiedViews/Plugins#269.

There might be an issue of l-rdfToCkan with duplicated resources sharing the same named graph URIs being created, which I [mention above](https://github.com/OpenDataNode/UVPlugin-rdfToCKAN/issues/3#issuecomment-120698191). If that turns out to be the case, I will create a separate issue for this problem.

Since the original problem with invalid SPARQL query was resolved, I'm closing this issue.
